### ISSUE TITLE
Is there any sample example?

### ISSUE THREAD

**Issue by ourway** [code3-coop/Garderie#1]
Hi, I try to use Carbon on my personal office but I failed to find any registration form.  Is there any ready to use sample of this CRM?

**Comment by benzen** [comment]
Hi,

This is not the project of carbon. 

Carbon mostly works.
It's an application that you need to install on your own server. Once installed all accounts will be accessible to all users.

We don't provide any demo at the moment.

If your are willing to give a hand on this project your help will be welcomed.
